---
# tasks file for tvheadend


- name: setup | all | ensure remote os supported
  fail: "Unsupported pkg mgr. This role is depends on apt."
  when: ansible_pkg_mgr not in ['apt']  


- include: setup-apt.yml
  sudo: Yes
  when: ansible_pkg_mgr == 'apt'
  tags: [ 'tvheadend', 'apt' ]


...